# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Codecov
        uses: codecov/codecov-action@v1.0.13
        with:
          # User defined upload name. Visible in Codecov UI
          name: Miya
          directory: ./
          env_vars: PYTHON
          fail_ci_if_error: false
          
      - name: Python Pylin GitHub Action
        uses: fylein/python-pylint-github-action@v1
        with:
          args: pip3 install -r requirements.txt && pylint --rcfile=.pylintrc ./
